# Generated by Django 2.1.3 on 2018-11-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnSapp', '0003_surveypost_usetemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='postNum',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='postNum',
            new_name='post',
        ),
    ]
