# Generated by Django 2.1.3 on 2018-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
    ]
