# Generated by Django 2.1.3 on 2018-11-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QnSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionNum', models.IntegerField(default=0)),
                ('studentNum', models.IntegerField(default=0)),
                ('answer', models.CharField(default='default', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNum', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=100)),
                ('department', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPost',
            fields=[
                ('postNum', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='default', max_length=500)),
                ('name', models.CharField(default='default', max_length=100)),
                ('subject', models.CharField(default='default', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionNum', models.IntegerField(default=0)),
                ('Question', models.CharField(default='default', max_length=500)),
                ('postNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QnSapp.SurveyPost')),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='Name',
        ),
        migrations.AddField(
            model_name='professor',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='password',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='answer',
            name='postNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QnSapp.SurveyPost'),
        ),
    ]
