# Generated by Django 2.1.3 on 2018-11-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnSapp', '0006_extraq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraq',
            name='starRate',
            field=models.FloatField(default=0.0),
        ),
    ]
